name: docs

on:
  # trigger deployment on every push to main branch
  push:
    branches: [main]
  # trigger deployment manually
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
          TARGET_REPO: EduardoProfe666/api-personalizada-wiki-vuepress # Reemplaza esto con el nombre de usuario y el nombre del repositorio objetivo
          TARGET_BRANCH: gh-pages # Cambia esto si deseas desplegar en otra rama
          BUILD_SCRIPT: yarn && yarn build
          BUILD_DIR: blog/.vuepress/dist/